functionality:
  name: process_task3_dataset
  namespace: match_modality_datasets
  version: dev
  description: |
    Censor an existing dataset: obfuscate gene names, remove cell identities and
    shuffle cells of modalities, for distribution to competitors.
  authors:
    - name: Louise Deconinck
      email: louise.deconinck@gmail.com
      roles: [ author, maintainer ]
      props: { github: LouiseDck, orcid: "" }
  arguments:
    - name: "--input_mod1"
      type: "file"
      example: "dataset.h5ad"
      description: "The first modality of the input dataset to be censored"
      required: true
    - name: "--input_mod2"
      type: "file"
      example: "dataset.h5ad"
      description: "The second modality of the input dataset to be censored"
      required: true
    - name: "--output_mod1"
      type: "file"
      direction: "output"
      example: "dataset_censored.h5ad"
      description: "A censored version of the first modality of the dataset."
      required: true
    - name: "--output_mod2"
      type: "file"
      direction: "output"
      example: "dataset_censored.h5ad"
      description: "A censored version of the second modality of the dataset."
      required: true
    - name: "--output_solution"
      type: "file"
      direction: "output"
      example: "dataset_solution.h5ad"
      description: "A solution of the dataset"
      required: true
  resources:
    - type: python_script
      path: script.py
  tests:
    - type: python_script
      path: test.py
    - path: ../../../../resources_test
platforms:
  - type: docker
    image: "python:3.8"
    setup: 
      - type: python
        packages: [ anndata, pandas, numpy ]
