functionality:
  name: baseline_babel
  namespace: predict_modality_methods
  version: dev
  description: A baseline method for comparing modality prediction methods against.
  authors:
    - name: Alejandro Granados
      email: alejandro.granados@czbiohub.org
      roles: [ author, maintainer ]
      props: { github: agranado}
  arguments:
    - name: "--input_mod1"
      type: "file"
      example: "dataset_mod1.h5ad"
      description: Censored dataset with train and test split.
      required: true
    - name: "--input_mod2"
      type: "file"
      example: "dataset_mod2.h5ad"
      description: Censored dataset with test data.
      required: true
    - name: "--output"
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: Dataset with prodicted values for modality2.
      required: true
    - name: "--mod1"
      type: "string"
      example: "RNA"
      description: "Modality to predict from"
      required: 'true'
    - name: "--data_id"
      type: "string"
      example: "granulocyte_multiome10x"
      description: "unique ID for dataset"
      required: 'true'
  resources:
    - type: r_script
      path: script.R
platforms:
  - type: docker
    image: dataintuitive/randpy:r4.0_py3.8_bioc3.12
    setup:
      - type: r
        packages: [ DropletUtils,nbHelpers]
  - type: nextflow
    directive_time: 10m
    directive_memory: "20 GB"
