functionality:
  name: asw_label
  namespace: joint_embedding_metrics
  version: dev
  description: Average silhouette width (ASW) of labels
  authors:
    - name: Michaela Mueller
      roles: [ maintainer, author ]
      props: { github: mumichae }
  arguments:
    - name: --input_prediction
      type: file
      description: Prediction by a method
      required: true
      example: prediction.h5ad
    - name: --input_solution
      type: file
      description: Gold standard solution.
      required: true
      example: solution.h5ad
    - name: --output
      type: file
      direction: output
      description: Metric scores by comparing the prediction to the gold standard solution.
      required: true
      example: output.h5ad
    - name: --debug
      type: boolean
      description: Verbose output for debugging.
      default: False
      required: false
  resources:
    - type: python_script
      path: script.py
  tests:
    - type: python_script
      path: test.py
    - path: ../../../../resources_test
platforms:
  - type: docker
    image: mumichae/scib-base:0.1
  - type: native
  - type: nextflow
    directive_time: 45m
