functionality:
  name: baseline_procrustes
  namespace: match_modality_methods
  version: dev
  description: A baseline method for comparing modality matching methods against.
  authors:
    - name: Alex Tong
      email: alexandertongdev@gmail.com
      roles: [ author, maintainer ]
      props: { github: atong01 }
  arguments:
    - name: "--input_mod1"
      alternatives: ["-i1"]
      type: "file"
      example: "dataset.h5ad"
      description: First modality of censored dataset.
      required: true
    - name: "--input_mod2"
      alternatives: ["-i2"]
      type: "file"
      example: "dataset.h5ad"
      description: Second modality of censored dataset.
      required: true
    - name: "--output"
      alternatives: ["-o"]
      type: "file"
      direction: "output"
      example: "output_rna.csv"
      description: Dataset with predicted values for modality2.
      required: true
    - name: "--n_svd"
      type: "integer"
      default: 100
      description: Number of SVD components to compress to
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: "python:3.8"
    setup:
      - type: python
        pip: [ anndata, scipy, sklearn ]
