functionality:
  name: "quality_control"
  namespace: "common_process_dataset"
  version: "dev"
  description: |
    Perform quality control of the cells and features in a dataset.
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input_rna"
      type: file
      description: "Raw dataset in a h5ad file."
      required: true
      example: "input.h5ad"
    - name: "--input_mod2"
      type: file
      description: "Raw dataset in a h5ad file."
      required: true
      example: "input.h5ad"
    - name: "--output_rna"
      type: file
      example: "output.h5ad"
      required: true
      direction: output
      description: Normalized h5ad file.
    - name: "--output_mod2"
      type: file
      example: "output.h5ad"
      required: true
      direction: output
      description: Normalized h5ad file.
    - name: "--min_counts_per_gene"
      type: integer
      default: 100
      description: "Minimum counts per gene."
    - name: "--min_counts_per_cell"
      type: integer
      default: 100
      description: "Minimum counts per cell."
  resources:
    - type: r_script
      path: script.R
  tests:
    - type: r_script
      path: test.R
    - path: ../../../../resources_test
platforms:
  - type: docker
    image: dataintuitive/randpy:r4.0_py3.8_bioc3.12
    setup:
      - type: python
        packages:
          - scanpy
      - type: r
        cran: 
          - anndata
  - type: nextflow
    publish: true
