functionality:
  name: censor_dataset
  namespace: match_modality_datasets
  version: dev
  description: |
    Censor an existing dataset: obfuscate gene names, remove cell identities and
    shuffle cells of modalities, for distribution to competitors.
  authors:
    - name: Louise Deconinck
      email: louise.deconinck@gmail.com
      roles: [ author, maintainer ]
      props: { github: LouiseDck, orcid: "" }
  arguments:
    - name: "--input_mod1"
      type: "file"
      example: "dataset.h5ad"
      description: "The first modality of the input dataset to be censored"
      required: true
    - name: "--input_mod2"
      type: "file"
      example: "dataset.h5ad"
      description: "The second modality of the input dataset to be censored"
      required: true
    - name: "--output_train_mod1"
      type: "file"
      direction: "output"
      example: "dataset_censored.h5ad"
      description: "The censored shuffled train mod1 profiles."
      required: true
    - name: "--output_train_mod2"
      type: "file"
      direction: "output"
      example: "dataset_censored.h5ad"
      description: "The censored shuffled train mod2 profiles."
      required: true
    - name: "--output_train_sol"
      type: "file"
      direction: "output"
      example: "dataset_solution.h5ad"
      description: "The pairing of train mod1&mod2 profiles."
      required: true
    - name: "--output_test_mod1"
      type: "file"
      direction: "output"
      example: "dataset_censored.h5ad"
      description: "The censored shuffled test mod1 profiles."
      required: true
    - name: "--output_test_mod2"
      type: "file"
      direction: "output"
      example: "dataset_censored.h5ad"
      description: "The censored shuffled test mod2 profiles."
      required: true
    - name: "--output_test_sol"
      type: "file"
      direction: "output"
      example: "dataset_solution.h5ad"
      description: "The pairing of test mod1&mod2 profiles."
      required: true
  resources:
    - type: python_script
      path: script.py
  tests:
    - type: python_script
      path: test.py
    - path: ../../../../resources_test
platforms:
  - type: docker
    image: "python:3.8"
    setup: 
      - type: python
        packages: [ anndata, pandas, numpy ]
  - type: nextflow
    publish: true