functionality:
  name: censor_dataset
  namespace: match_modality_datasets
  version: dev
  description: |
    Censor an existing dataset: obfuscate gene names, remove cell identities and
    shuffle cells of modalities, for distribution to competitors.
  authors:
    - name: Louise Deconinck
      email: louise.deconinck@gmail.com
      roles: [ author, maintainer ]
      props: { github: LouiseDck, orcid: "" }
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ contributor ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input_mod1"
      type: "file"
      example: "dataset.h5ad"
      description: "The first modality of the input dataset to be censored"
      required: true
    - name: "--input_mod2"
      type: "file"
      example: "dataset.h5ad"
      description: "The second modality of the input dataset to be censored"
      required: true
    - name: "--output_train_mod1"
      type: "file"
      direction: "output"
      example: "dataset_censored.h5ad"
      description: "The censored shuffled train mod1 profiles."
      required: true
    - name: "--output_train_mod2"
      type: "file"
      direction: "output"
      example: "dataset_censored.h5ad"
      description: "The censored shuffled train mod2 profiles."
      required: true
    - name: "--output_train_sol"
      type: "file"
      direction: "output"
      example: "dataset_solution.h5ad"
      description: "The pairing of train mod1&mod2 profiles."
      required: true
    - name: "--output_test_mod1"
      type: "file"
      direction: "output"
      example: "dataset_censored.h5ad"
      description: "The censored shuffled test mod1 profiles."
      required: true
    - name: "--output_test_mod2"
      type: "file"
      direction: "output"
      example: "dataset_censored.h5ad"
      description: "The censored shuffled test mod2 profiles."
      required: true
    - name: "--output_test_sol"
      type: "file"
      direction: "output"
      example: "dataset_solution.h5ad"
      description: "The pairing of test mod1&mod2 profiles."
      required: true
    - name: "--knn"
      type: "integer"
      default: 20
      description: The KNN cutoff for computing nearest neighbors on the mod1 and mod2 profiles.
    - name: "--seed"
      type: "integer"
      default: 1
      description: The seed.
  resources:
    - type: r_script
      path: script.R
platforms:
  - type: docker
    image: dataintuitive/randpy:r4.0_py3.8_bioc3.12
    setup:
      - type: r
        cran: [ anndata ]
      - type: python
        packages: [ anndata ]
  - type: nextflow
    publish: true
    labels: [ highmem, midtime, highcpu ]
