functionality:
  name: baseline_pca
  namespace: match_modality_methods
  version: dev
  description: A baseline method for comparing modality matching methods against.
  authors:
    - name: Louise Deconinck
      email: louise.deconinck@gmail.com
      roles: [ author, maintainer ]
      props: { github: LouiseDck }
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: "file"
      example: "dataset.h5ad"
      description: Censored dataset.
      required: true
    - name: "--prediction"
      alternatives: ["-o"]
      type: "file"
      direction: "output"
      example: "output_rna.csv"
      description: Dataset with prodicted values for modality2.
      required: true
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: "python:3.8"
    setup:
      - type: python
        pip: [ anndata, scipy, sklearn ]