functionality:
  name: baseline_randomforest
  namespace: predict_modality_methods
  version: dev
  description: A baseline method for comparing modality prediction methods against.
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author, maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: "file"
      example: "dataset.h5ad"
      description: Censored dataset.
      required: true
    - name: "--output"
      alternatives: ["-o"]
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: Dataset with prodicted values for modality2.
      required: true
  resources:
    - type: r_script
      path: script.R
  tests:
    - type: r_script
      path: test.R
    - path: ../../../../resources/test/dyngen_bifurcating_atac/dataset_task1_censored.h5ad
platforms:
  - type: docker
    image: dataintuitive/randpy:r4.0_py3.8_bioc3.12
    setup:
      - type: r
        packages: [ randomForest ]
  - type: nextflow
