functionality:
  name: download_azimuth_dataset
  namespace: common_datasets
  version: dev
  description: Download CITE-seq data from Azimuth reference
  usage: |
    download_azimuth_dataset \
      --id azimuth_ref \
      --input_count https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE164378&format=file \
      --input_meta https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE164378&format=file&file=GSE164378%5Fsc%2Emeta%2Edata%5F3P%2Ecsv%2Egz \
      --out_raw_count resources_test_2/common/azimuth_raw/GSE164378_RAW.tar \
      --out_raw_meta resources_test_2/common/azimuth_raw/GSE164378_sc.meta.data_3P.csv.gz \
      --output_rna resources_test_2/common/azimuth_ref_output_rna.h5ad \
      --output_mod2 resources_test_2/common/azimuth_ref_output_mod2.h5ad
  authors:
    - name: Christopher Lance
      email: clance.connect@gmail.com
      roles: [ author, maintainer ]
      props: { github: xlancelottx }
  arguments:
    - name: --id
      type: string
      example: azimuth_ref
      description: The id of the output dataset id
      required: true
    - name: --input_count
      type: string
      description: Location URL to the GEO raw counts tar file
      required: true
      example: "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE164378&format=file"
    - name: --input_meta
      type: string
      description: Location URL to the GEO meta data file
      required: true
      example: "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE164378&format=file&file=GSE164378%5Fsc%2Emeta%2Edata%5F3P%2Ecsv%2Egz"
    - name: "--organism"
      type: string
      description: "The organism of the dataset"
      required: true
      example: "human"
    - name: "--output_rna"
      type: file
      example: output_rna.h5ad
      required: true
      direction: output
      description: Output h5ad RNA file.
    - name: "--output_mod2"
      type: file
      example: output_mod2.h5ad
      required: true
      direction: output
      description: Output h5ad modality2 file (ATAC or Antibody capture).
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: "python:3.8"
    setup:
      - type: python
        pip: [ anndata, scanpy, scipy ]
  - type: nextflow
