functionality:
  name: dummy_solution
  namespace: joint_embedding_methods
  version: dev
  description: A dummy method which returns an embedding based on the solution
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author, maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input_solution"
      type: "file"
      example: "dataset_solution.h5ad"
      description: Censored dataset.
      required: true
    - name: "--output"
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: Dataset with predicted values for modality2.
      required: true
  resources:
    - type: r_script
      path: script.R
  tests:
    - type: r_script
      path: test_method.R
    - path: ../../../../resources_test
platforms:
  - type: docker
    image: dataintuitive/randpy:r4.0_py3.8_bioc3.12
    setup:
      - type: r
        packages: [ dyndimred ]
  - type: nextflow
    labels: [ lowmem, lowtime, lowcpu ]
