functionality:
  name: dummy_constant
  namespace: match_modality_methods
  version: dev
  description: A baseline method for comparing modality matching methods against. Outputs a matrix of constant value (equal pairing probability)
  authors:
    - name: Alex Tong
      email: alexandertongdev@gmail.com
      roles: [ author, maintainer ]
      props: { github: atong01 }
  arguments:
    - name: "--input_train_mod1"
      type: "file"
      example: "dataset_censored.h5ad"
      description: "The censored shuffled train mod1 profiles."
      required: true
    - name: "--input_train_mod2"
      type: "file"
      example: "dataset_censored.h5ad"
      description: "The censored shuffled train mod2 profiles."
      required: true
    - name: "--input_train_sol"
      type: "file"
      example: "dataset_solution.h5ad"
      description: "The pairing of train mod1&mod2 profiles."
      required: true
    - name: "--input_test_mod1"
      type: "file"
      example: "dataset_censored.h5ad"
      description: "The censored shuffled test mod1 profiles."
      required: true
    - name: "--input_test_mod2"
      type: "file"
      example: "dataset_censored.h5ad"
      description: "The censored shuffled test mod2 profiles."
      required: true
    - name: "--output"
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: "The predicted pairing of test mod1&mod2 profiles."
      required: true
  resources:
    - type: python_script
      path: script.py
  tests:
    - type: python_script
      path: ../../unit_tests/test_method.py
    - path: ../../../../resources_test
platforms:
  - type: docker
    image: "python:3.8"
    setup:
      - type: python
        pip: [ anndata, numpy ]
  - type: nextflow
    labels: [ lowmem, lowtime, lowcpu ]