functionality:
  name: check_format
  namespace: predict_modality_metrics
  version: dev
  description: Checking whether the prediction of a method has the right format.
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author, maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: --input_prediction
      type: file
      description: Prediction by a method
      required: true
      example: prediction.h5ad
    - name: "--input_solution"
      type: "file"
      example: "solution.h5ad"
      description: Gold standard solution
      required: true
    - name: --output
      type: file
      direction: output
      description: Metric scores by comparing the prediction to the gold standard solution.
      required: true
      example: output.h5ad
  resources:
    - type: r_script
      path: script.R
  tests:
    - type: python_script
      path: ../../unit_tests/test_metric.py
    - path: ../../../../resources_test
platforms:
  - type: docker
    image: dataintuitive/randpy:r4.0_py3.8_bioc3.12
  - type: nextflow
    directive_time: 45m
