functionality:
  name: dummy_constant
  namespace: predict_modality_methods
  version: dev
  description: A baseline method for comparing modality prediction methods against. Predicts the mean training vector
  authors:
    - name: Alex Tong
      email: alexandertongdev@gmail.com
      roles: [ author, maintainer ]
      props: { github: atong01 }
  arguments:
    - name: "--input_train_mod1"
      alternatives: ["-i1"]
      type: "file"
      example: "dataset_mod1_train.h5ad"
      description: Censored dataset, training cells.
      required: true
    - name: "--input_test_mod1"
      alternatives: ["-i1"]
      type: "file"
      example: "dataset_mod1_test.h5ad"
      description: Censored dataset, test cells.
      required: true
    - name: "--input_train_mod2"
      alternatives: ["-i2"]
      type: "file"
      example: "dataset_mod2.h5ad"
      description: Censored dataset.
      required: true
    - name: "--output"
      alternatives: ["-o"]
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: Dataset with predicted values for modality2.
      required: true
  resources:
    - type: python_script
      path: script.py
  tests:
    - type: python_script
      path: ../../unit_tests/test_method.py
    - path: ../../../../resources_test
platforms:
  - type: docker
    image: "python:3.8"
    setup:
      - type: python
        pip: [ anndata, scipy, sklearn ]
  - type: nextflow
    labels: [ lowmem, lowtime, lowcpu ]
