functionality:
  name: dummy_zeros
  namespace: predict_modality_methods
  version: dev
  description: A baseline method for comparing modality prediction methods against. Predicts mean training value for mod2 for all test points.
  authors:
    - name: Alex Tong
      email: alexandertongdev@gmail.com
      roles: [ author, maintainer ]
      props: { github: atong01 }
  arguments:
    - name: "--input_train_mod1"
      type: "file"
      example: "dataset_mod1.h5ad"
      description: Censored dataset.
      required: true
    - name: "--input_test_mod1"
      type: "file"
      example: "dataset_mod2.h5ad"
      description: Censored dataset.
      required: true
    - name: "--input_train_mod2"
      type: "file"
      example: "dataset_mod2.h5ad"
      description: Censored dataset, train cells.
      required: true
    - name: "--output"
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: Dataset with predicted values for modality2.
      required: true
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: "python:3.8"
    setup:
      - type: python
        pip: [ anndata, scipy ]
  - type: nextflow
    directive_time: 10m
