functionality:
  name: baseline_dr_nn_ga
  namespace: match_modality_methods
  version: dev
  description: Perform LMDS+Pearson DR, predict embedding with Keras NN, and match cells with a GA to minimise pairwise distances.
  info:
    type: baseline
    label: LMDS+NN+GA
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author, maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input_train_mod1"
      type: "file"
      example: "dataset_censored.h5ad"
      description: "The censored shuffled train mod1 profiles."
      required: true
    - name: "--input_train_mod2"
      type: "file"
      example: "dataset_censored.h5ad"
      description: "The censored shuffled train mod2 profiles."
      required: true
    - name: "--input_train_sol"
      type: "file"
      example: "dataset_solution.h5ad"
      description: "The pairing of train mod1&mod2 profiles."
      required: true
    - name: "--input_test_mod1"
      type: "file"
      example: "dataset_censored.h5ad"
      description: "The censored shuffled test mod1 profiles."
      required: true
    - name: "--input_test_mod2"
      type: "file"
      example: "dataset_censored.h5ad"
      description: "The censored shuffled test mod2 profiles."
      required: true
    - name: "--distance_method"
      type: "string"
      default: "spearman"
      description: The distance method to use. Possible values are euclidean, pearson, spearman and others.
    - name: "--n_dims"
      type: "integer"
      default: 10
      description: Number of dimensions to use.
    - name: "--n_ga_pop"
      type: "integer"
      default: 50
      description: Population size of genetic algorithm.
    - name: "--n_ga_iter"
      type: "integer"
      default: 100
      description: Number of GA iterations to perform.
    - name: "--output"
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: "The predicted pairing of test mod1&mod2 profiles."
      required: true
  resources:
    - type: r_script
      path: script.R
  tests:
    - type: r_script
      path: ../../unit_tests/test_method.R
    - path: ../../../../resources_test
platforms:
  - type: docker
    image: dataintuitive/randpy:r4.0_py3.8_bioc3.12
    setup:
      - type: r
        packages: [ lmds, dynutils, keras, GA ]
      - type: python
        packages: [ tensorflow ]
  - type: nextflow
    labels: [ lowmem, lowtime, lowcpu ]
