functionality:
  name: censor_task1
  namespace: predict_modality_datasets
  version: dev
  description: |
    A component for censoring modality alignment datasets to be given
    to competition participants for the 'predict modality' task.
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author, maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: "file"
      example: "dataset.h5ad"
      description: |
        An input h5ad dataset, containing the following objects:
          * ad.X: mRNA counts
          * ad.layers['atac']: ATAC data
          * ad.layers['antibody']: Antibody data
        Either the ATAC layer or the Antibody layer must be defined, but not neither or both.
      required: true
    - name: "--output"
      alternatives: ["-o"]
      type: "file"
      direction: "output"
      example: "dataset_censored.h5ad"
      description: |
        Where to store the censored h5ad dataset, containing the following objects:
          * ad.layers['modality1']: Predictor modality, either the ATAC or the mRNA data.
          * ad.layers['modality2']: Response modality, either the mRNA or the antibody data.
          * ad.var['is_predictor']: Whether feature is a predictor
          * ad.var['is_response']: Whether feature is a response (needs to be predicted)
      required: true
  resources:
    - type: r_script
      path: script.R
  tests:
    - type: r_script
      path: test.R
    - path: ../../../../resources/test/dyngen_bifurcating_atac/dataset.h5ad
platforms:
  - type: docker
    image: dataintuitive/randpy:r4.0_py3.8_bioc3.12
