functionality:
  name: totalvi_metrics
  namespace: joint_embedding_metrics
  version: dev
  description: Calculate latent mixing metric for joint embedding task.
  authors:
    - name: Ann Chen
      email: ann.chen@czbiohub.org
      roles: [ author, maintainer ]
      props: { github: atchen}
  arguments:
    - name: "--input_prediction"
      alternatives: ["-ip"]
      type: "file"
      example: "prediction.h5ad"
      description: Prediction by a method
      required: true
      multiple: true
    - name: "--input_solution"
      alternatives: ["-io"]
      type: "file"
      example: "solution.h5ad"
      description: Gold standard solution
      required: true
      multiple: true
    - name: "--output"
      alternatives: ["-o"]
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: Latent mixing metric measures how well the latent cell representations are mixed between batches relative to the global frequency of batches.
      required: true
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: "python:3.8"
    setup:
      - type: python
        pip: [ anndata, scvi ]