functionality:
  name: totalvi_metrics
  namespace: joint_embedding_metrics
  version: dev
  description: Calculate four totalvi metrics (latent mixing, feature retention, clustering, and measurement mixing) for the joint embedding task.
  authors:
    - name: Ann Chen
      email: ann.chen@czbiohub.org
      roles: [ author, maintainer ]
      props: { github: atchen}
  arguments:
    - name: "--input_mod1"
      alternatives: ["-i1"]
      type: "file"
      example: "dataset.h5ad"
      description: First datset
    - name: "--input_mod2"
      alternatives: ["-i2"]
      type: "file"
      example: "dataset.h5ad"
      description: Second dataset
      required: true
    - name: "--output"
      alternatives: ["-o"]
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: totalvi metrics
      required: true
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: "python:3.8"
    setup:
      - type: python
        pip: [ anndata, scipy, sklearn, scvi ]