functionality:
  name: rf_oob
  namespace: joint_embedding_metrics
  version: dev
  description: Calculating basic metrics for the joint embedding task.
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author, maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:

    - name: --input_prediction
      type: file
      description: Prediction by a method
      required: true
      example: prediction.h5ad
    - name: --input_solution
      type: file
      description: Gold standard solution.
      required: true
      example: solution.h5ad
    - name: --output
      type: file
      direction: output
      description: Metric scores by comparing the prediction to the gold standard solution.
      required: true
      example: output.h5ad
  resources:
    - type: r_script
      path: script.R
  tests:
    - type: python_script
      path: ../../unit_tests/test_metric.py
    - path: ../../../../resources_test
    - path: metric_meta_rf_oob.tsv
      dest: metric_meta.tsv
platforms:
  - type: docker
    image: dataintuitive/randpy:r4.0_py3.8_bioc3.12
    setup: 
      - type: r
        packages: [ ranger ]
  - type: nextflow
    labels: [ lowmem, lowtime, lowcpu ]