functionality:
  name: totalvi
  namespace: joint_embedding_methods
  version: dev
  description: totalVI for comparing joint embedding methods against.
  authors:
    - name: Christopher Lance
      email: clance.connect@gmail.com
      roles: [ author, maintainer ]
      props: { github: xlancelottx }
  arguments:
    - name: "--input_mod1"
      type: "file"
      example: "dataset_mod1.h5ad"
      description: Censored dataset.
      required: true
    - name: "--input_mod2"
      type: "file"
      example: "dataset_mod2.h5ad"
      description: Censored dataset.
      required: true
<<<<<<< HEAD
    - name: "--output_prediction"
=======
    - name: "--output"
>>>>>>> edae9d252a0fc73fb6e206eab486966d5c914e08
      type: "file"
      direction: "output"
      example: "output.h5ad"
      description: Dataset containing integrated embedding
      required: true
    - name: "--hvg_number"
      type: "integer"
      default: 4000
      description: Number of HVG to include in totalVI
    - name: "--max_epochs"
      type: "integer"
      default: 400
      description: Number of HVG to include in totalVI
  resources:
    - type: python_script
      path: script.py
<<<<<<< HEAD
  tests:
    - type: python_script
      path: test.py
    - path: ../../../../resources_test_2
=======
>>>>>>> edae9d252a0fc73fb6e206eab486966d5c914e08
platforms:
  - type: docker
    image: "python:3.8"
    setup:
      - type: python
<<<<<<< HEAD
        pip: [ anndata, scanpy, scikit-misc, scipy, scikit-learn, scvi-tools]
=======
        pip: [ anndata, scanpy, scipy, scikit-misc, scvi-tools]
      #- type: nextflow
>>>>>>> edae9d252a0fc73fb6e206eab486966d5c914e08


